### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by jakobkukla** [i3roly/CMI8788#2]
Hi,

I'm wondering if you're still working on this and if it's working yet. If yes, could you help me compiling it? Is it even the right driver for the Xonar DX?

Thanks

**Comment by jakobkukla** [comment]
@i3roly I tried to compile it in Xcode but got an error.

`In file included from /Users/jakob/Documents/CMI8788/CMI8788/XonarHDAVAudioEngine.cpp:49:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Kernel.framework/Headers/IOKit/IOLib.h:44:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Kernel.framework/Headers/IOKit/system.h:57:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Kernel.framework/Headers/libkern/libkern.h:145:12: error: conflicting types for 'ffsll'
extern int      ffsll(unsigned long long);
                ^
In file included from /Users/jakob/Documents/CMI8788/CMI8788/XonarHDAVAudioEngine.cpp:47:
In file included from /usr/include/string.h:180:
/usr/include/strings.h:86:6: note: previous declaration is here
int      ffsll(long long) __OSX_AVAILABLE_STARTING(__MAC_10_9, __IPHONE_7_0);
         ^
In file included from /Users/jakob/Documents/CMI8788/CMI8788/XonarHDAVAudioEngine.cpp:49:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Kernel.framework/Headers/IOKit/IOLib.h:44:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Kernel.framework/Headers/IOKit/system.h:57:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Kernel.framework/Headers/libkern/libkern.h:147:12: error: conflicting types for 'flsll'
extern int      flsll(unsigned long long);`

**Comment by i3roly** [comment]
sorry, i just saw this.

please try the latest version and see if the error goes away.

i had too many inclusions and have whittled them down. hopefully it is gone now.

**Comment by i3roly** [comment]
the issue you experienced was due to the unnecessary inclusion of </usr/include/string.h> instead of just string.h

i have cleaned up the includes in commit a4af00929f47dd73f8cba0fc98b5398be1f698ed so it should compile without issue now. i have personally tested this by making a Sierra install and then cloning the repository, and it compiled fine.

please open a new ticket if there are still issues.
