### ISSUE TITLE
What is the current state of this driver?

### ISSUE THREAD

**Issue by jakobkukla** [i3roly/CMI8788#3]
So I could compile without any errors like you said. I put the kext in my EFI and booted successfully to my surprise. Anyways, there is no change. Still no audio.

What should I expect from this driver at the moment. Is the audio output for you working? Can I help you in any way? I have a Xonar DX btw.

**Comment by i3roly** [comment]
i appreciate your eagerness. while all of the initialisation code is there, i am in the process of testing it.

at this point i need to fix the lock allocations, the ac97_wait/read/write functions, and then start adding the streams/mixers/dials/volumes. 

this is no easy task given these sounds cards' rich feature set. i have an  HDAV1.3+H6 and i am thrilled it is getting detected as you would expect. 

but porting something this complex to a different kernel will take time. i cannot give you an eta. all i can say is you are loading this kext at your own peril. i do not have sound working at this time, and i suspect when i do: you'll hear about it without asking on the github (yes, it's that big of a deal)...
